// Auto-generated by build_timings.py — do not edit by hand
const TIMINGS = {
  "2": {
    "bg_v": {
      "narrator": "Naxos audiobook, narrated by Neville Jason",
      "duration": 94732.98,
      "anchors": [
        {
          "page": 1,
          "seconds": 15.84
        },
        {
          "page": 5,
          "seconds": 588.24
        },
        {
          "page": 10,
          "seconds": 1340.34
        },
        {
          "page": 15,
          "seconds": 2066.58
        },
        {
          "page": 20,
          "seconds": 2802.6
        },
        {
          "page": 25,
          "seconds": 3558.84
        },
        {
          "page": 30,
          "seconds": 4302.42
        },
        {
          "page": 35,
          "seconds": 5045.46
        },
        {
          "page": 40,
          "seconds": 5830.44
        },
        {
          "page": 45,
          "seconds": 6614.52
        },
        {
          "page": 50,
          "seconds": 7367.46
        },
        {
          "page": 55,
          "seconds": 8178.72
        },
        {
          "page": 60,
          "seconds": 8925.48
        },
        {
          "page": 65,
          "seconds": 9673.32
        },
        {
          "page": 70,
          "seconds": 10432.92
        },
        {
          "page": 75,
          "seconds": 11232.06
        },
        {
          "page": 80,
          "seconds": 11982.84
        },
        {
          "page": 85,
          "seconds": 12776.34
        },
        {
          "page": 90,
          "seconds": 13514.04
        },
        {
          "page": 95,
          "seconds": 14257.38
        },
        {
          "page": 100,
          "seconds": 14978.28
        },
        {
          "page": 105,
          "seconds": 15739.38
        },
        {
          "page": 110,
          "seconds": 16542
        },
        {
          "page": 115,
          "seconds": 17295.72
        },
        {
          "page": 120,
          "seconds": 18045.72
        },
        {
          "page": 125,
          "seconds": 18828.36
        },
        {
          "page": 130,
          "seconds": 19594.08
        },
        {
          "page": 135,
          "seconds": 20333.22
        },
        {
          "page": 140,
          "seconds": 21053.34
        },
        {
          "page": 145,
          "seconds": 21858.3
        },
        {
          "page": 150,
          "seconds": 22632.72
        },
        {
          "page": 155,
          "seconds": 23409.78
        },
        {
          "page": 160,
          "seconds": 24150.84
        },
        {
          "page": 165,
          "seconds": 24914.1
        },
        {
          "page": 170,
          "seconds": 25672.86
        },
        {
          "page": 175,
          "seconds": 26405.4
        },
        {
          "page": 180,
          "seconds": 27158.28
        },
        {
          "page": 185,
          "seconds": 27959.76
        },
        {
          "page": 190,
          "seconds": 28723.5
        },
        {
          "page": 195,
          "seconds": 29486.16
        },
        {
          "page": 200,
          "seconds": 30247.86
        },
        {
          "page": 205,
          "seconds": 30997.56
        },
        {
          "page": 210,
          "seconds": 31725.06
        },
        {
          "page": 215,
          "seconds": 32505.3
        },
        {
          "page": 220,
          "seconds": 33297.42
        },
        {
          "page": 225,
          "seconds": 34068.6
        },
        {
          "page": 230,
          "seconds": 34871.16
        },
        {
          "page": 235,
          "seconds": 35661.48
        },
        {
          "page": 240,
          "seconds": 36472.86
        },
        {
          "page": 245,
          "seconds": 37266.9
        },
        {
          "page": 250,
          "seconds": 38061.78
        },
        {
          "page": 255,
          "seconds": 38733.66
        },
        {
          "page": 260,
          "seconds": 39501
        },
        {
          "page": 265,
          "seconds": 40249.74
        },
        {
          "page": 270,
          "seconds": 41038.32
        },
        {
          "page": 275,
          "seconds": 41881.08
        },
        {
          "page": 280,
          "seconds": 42630.24
        },
        {
          "page": 285,
          "seconds": 43408.14
        },
        {
          "page": 290,
          "seconds": 44191.38
        },
        {
          "page": 295,
          "seconds": 44938.98
        },
        {
          "page": 300,
          "seconds": 45666.24
        },
        {
          "page": 305,
          "seconds": 46437.36
        },
        {
          "page": 310,
          "seconds": 47168.34
        },
        {
          "page": 315,
          "seconds": 47896.44
        },
        {
          "page": 320,
          "seconds": 48655.8
        },
        {
          "page": 325,
          "seconds": 49428.54
        },
        {
          "page": 330,
          "seconds": 50182.92
        },
        {
          "page": 335,
          "seconds": 50933.16
        },
        {
          "page": 340,
          "seconds": 51714.12
        },
        {
          "page": 345,
          "seconds": 52498.68
        },
        {
          "page": 350,
          "seconds": 53274
        },
        {
          "page": 355,
          "seconds": 54010.98
        },
        {
          "page": 360,
          "seconds": 54791.1
        },
        {
          "page": 365,
          "seconds": 55559.34
        },
        {
          "page": 370,
          "seconds": 56332.14
        },
        {
          "page": 375,
          "seconds": 57126.3
        },
        {
          "page": 380,
          "seconds": 57930.54
        },
        {
          "page": 385,
          "seconds": 58694.16
        },
        {
          "page": 390,
          "seconds": 59470.68
        },
        {
          "page": 395,
          "seconds": 60237.54
        },
        {
          "page": 400,
          "seconds": 61007.82
        },
        {
          "page": 405,
          "seconds": 61747.74
        },
        {
          "page": 410,
          "seconds": 62492.58
        },
        {
          "page": 415,
          "seconds": 63312.9
        },
        {
          "page": 420,
          "seconds": 64088.64
        },
        {
          "page": 425,
          "seconds": 64852.62
        },
        {
          "page": 430,
          "seconds": 65638.44
        },
        {
          "page": 435,
          "seconds": 66403.86
        },
        {
          "page": 440,
          "seconds": 67191.6
        },
        {
          "page": 445,
          "seconds": 67981.08
        },
        {
          "page": 450,
          "seconds": 68755.92
        },
        {
          "page": 455,
          "seconds": 69506.46
        },
        {
          "page": 460,
          "seconds": 70276.2
        },
        {
          "page": 465,
          "seconds": 71025.36
        },
        {
          "page": 470,
          "seconds": 71775.54
        },
        {
          "page": 475,
          "seconds": 72555.12
        },
        {
          "page": 480,
          "seconds": 73298.94
        },
        {
          "page": 485,
          "seconds": 74074.38
        },
        {
          "page": 490,
          "seconds": 74846.82
        },
        {
          "page": 495,
          "seconds": 75610.74
        },
        {
          "page": 500,
          "seconds": 76444.74
        },
        {
          "page": 505,
          "seconds": 77224.92
        },
        {
          "page": 510,
          "seconds": 77983.14
        },
        {
          "page": 515,
          "seconds": 78798.48
        },
        {
          "page": 520,
          "seconds": 79528.08
        },
        {
          "page": 525,
          "seconds": 80301.96
        },
        {
          "page": 530,
          "seconds": 81066.66
        },
        {
          "page": 535,
          "seconds": 81825
        },
        {
          "page": 540,
          "seconds": 82549.62
        },
        {
          "page": 545,
          "seconds": 83305.92
        },
        {
          "page": 550,
          "seconds": 84099.42
        },
        {
          "page": 555,
          "seconds": 84896.7
        },
        {
          "page": 560,
          "seconds": 85645.44
        },
        {
          "page": 565,
          "seconds": 86452.8
        },
        {
          "page": 570,
          "seconds": 87214.62
        },
        {
          "page": 575,
          "seconds": 87986.1
        },
        {
          "page": 580,
          "seconds": 88788.36
        },
        {
          "page": 585,
          "seconds": 89554.8
        },
        {
          "page": 590,
          "seconds": 90348.96
        },
        {
          "page": 595,
          "seconds": 91155.36
        },
        {
          "page": 600,
          "seconds": 91896.66
        },
        {
          "page": 605,
          "seconds": 92656.68
        },
        {
          "page": 610,
          "seconds": 93446.64
        },
        {
          "page": 615,
          "seconds": 94206.78
        }
      ]
    }
  },
  "3": {
    "gw_v": {
      "narrator": "Naxos audiobook, narrated by Neville Jason",
      "duration": 103698.366984,
      "anchors": [
        {
          "page": 1,
          "seconds": 0
        },
        {
          "page": 3.6,
          "seconds": 389.537959
        },
        {
          "page": 5.4,
          "seconds": 666.133923
        },
        {
          "page": 8.7,
          "seconds": 1158.860907
        },
        {
          "page": 11.6,
          "seconds": 1602.686893
        },
        {
          "page": 14.1,
          "seconds": 1995.521859
        },
        {
          "page": 16.4,
          "seconds": 2349.393832
        },
        {
          "page": 19.1,
          "seconds": 2766.981814
        },
        {
          "page": 22.2,
          "seconds": 3228.03678
        },
        {
          "page": 24.3,
          "seconds": 3548.42576
        },
        {
          "page": 30.5,
          "seconds": 4495.010748
        },
        {
          "page": 34,
          "seconds": 5029.394739
        },
        {
          "page": 38.8,
          "seconds": 5741.458685
        },
        {
          "page": 41.5,
          "seconds": 6152.451655
        },
        {
          "page": 48.3,
          "seconds": 7210.306621
        },
        {
          "page": 52.5,
          "seconds": 7889.165578
        },
        {
          "page": 55.2,
          "seconds": 8307.217551
        },
        {
          "page": 58.1,
          "seconds": 8719.836508
        },
        {
          "page": 61,
          "seconds": 9155.071474
        },
        {
          "page": 63.4,
          "seconds": 9511.776463
        },
        {
          "page": 65.3,
          "seconds": 9796.081451
        },
        {
          "page": 67.6,
          "seconds": 10163.467438
        },
        {
          "page": 70.3,
          "seconds": 10586.99941
        },
        {
          "page": 72.6,
          "seconds": 10942.914376
        },
        {
          "page": 75.7,
          "seconds": 11417.344354
        },
        {
          "page": 79.6,
          "seconds": 11996.31034
        },
        {
          "page": 82.1,
          "seconds": 12364.671338
        },
        {
          "page": 85.1,
          "seconds": 12788.342313
        },
        {
          "page": 88.1,
          "seconds": 13245.496281
        },
        {
          "page": 91.6,
          "seconds": 13792.837279
        },
        {
          "page": 94.7,
          "seconds": 14272.933243
        },
        {
          "page": 97.2,
          "seconds": 14641.805215
        },
        {
          "page": 99.9,
          "seconds": 15041.281179
        },
        {
          "page": 105.7,
          "seconds": 15893.082132
        },
        {
          "page": 110.6,
          "seconds": 16587.173107
        },
        {
          "page": 113,
          "seconds": 16918.893107
        },
        {
          "page": 118.9,
          "seconds": 17798.41805
        },
        {
          "page": 123.1,
          "seconds": 18426.982041
        },
        {
          "page": 127.2,
          "seconds": 19036.32
        },
        {
          "page": 129.9,
          "seconds": 19426.182993
        },
        {
          "page": 132.8,
          "seconds": 19868.847982
        },
        {
          "page": 136.3,
          "seconds": 20398.030975
        },
        {
          "page": 139.1,
          "seconds": 20804.751973
        },
        {
          "page": 141.3,
          "seconds": 21118.453968
        },
        {
          "page": 145.1,
          "seconds": 21693.054921
        },
        {
          "page": 148.2,
          "seconds": 22159.914921
        },
        {
          "page": 153.9,
          "seconds": 23054.161859
        },
        {
          "page": 155.6,
          "seconds": 23315.107846
        },
        {
          "page": 158.4,
          "seconds": 23762.741814
        },
        {
          "page": 163.4,
          "seconds": 24537.870748
        },
        {
          "page": 168.9,
          "seconds": 25390.275692
        },
        {
          "page": 171.4,
          "seconds": 25781.856689
        },
        {
          "page": 176.5,
          "seconds": 26594.183673
        },
        {
          "page": 183.7,
          "seconds": 27757.131655
        },
        {
          "page": 186.9,
          "seconds": 28244.146621
        },
        {
          "page": 188.7,
          "seconds": 28524.132608
        },
        {
          "page": 191.3,
          "seconds": 28881.069569
        },
        {
          "page": 194.4,
          "seconds": 29318.626531
        },
        {
          "page": 197.8,
          "seconds": 29848.598503
        },
        {
          "page": 200.3,
          "seconds": 30217.563492
        },
        {
          "page": 203.6,
          "seconds": 30643.603492
        },
        {
          "page": 206.8,
          "seconds": 31117.476463
        },
        {
          "page": 213.4,
          "seconds": 32100.145442
        },
        {
          "page": 216.8,
          "seconds": 32624.544399
        },
        {
          "page": 219.2,
          "seconds": 32973.493379
        },
        {
          "page": 224.7,
          "seconds": 33833.142313
        },
        {
          "page": 227.5,
          "seconds": 34254.35229
        },
        {
          "page": 230.7,
          "seconds": 34749.634286
        },
        {
          "page": 233.8,
          "seconds": 35240.550249
        },
        {
          "page": 237.3,
          "seconds": 35756.637234
        },
        {
          "page": 240.2,
          "seconds": 36186.99619
        },
        {
          "page": 242.5,
          "seconds": 36536.410159
        },
        {
          "page": 245.1,
          "seconds": 36886.520136
        },
        {
          "page": 247.3,
          "seconds": 37214.804127
        },
        {
          "page": 250.1,
          "seconds": 37641.819093
        },
        {
          "page": 252.8,
          "seconds": 38000.14907
        },
        {
          "page": 255.7,
          "seconds": 38425.492063
        },
        {
          "page": 258.4,
          "seconds": 38865.324036
        },
        {
          "page": 261.1,
          "seconds": 39267.076009
        },
        {
          "page": 266.2,
          "seconds": 39974.913923
        },
        {
          "page": 271.4,
          "seconds": 40771.451882
        },
        {
          "page": 277.8,
          "seconds": 41751.612834
        },
        {
          "page": 280.4,
          "seconds": 42140.593832
        },
        {
          "page": 282.2,
          "seconds": 42408.92381
        },
        {
          "page": 284.6,
          "seconds": 42766.789796
        },
        {
          "page": 287.9,
          "seconds": 43304.65678
        },
        {
          "page": 290.4,
          "seconds": 43667.212744
        },
        {
          "page": 293,
          "seconds": 44049.08771
        },
        {
          "page": 295.4,
          "seconds": 44413.919683
        },
        {
          "page": 298.9,
          "seconds": 44939.015646
        },
        {
          "page": 302.2,
          "seconds": 45483.523628
        },
        {
          "page": 304.6,
          "seconds": 45849.423583
        },
        {
          "page": 306.8,
          "seconds": 46184.115556
        },
        {
          "page": 308.9,
          "seconds": 46524.659546
        },
        {
          "page": 311.1,
          "seconds": 46864.506531
        },
        {
          "page": 313.1,
          "seconds": 47160.096508
        },
        {
          "page": 315.7,
          "seconds": 47543.039501
        },
        {
          "page": 318.9,
          "seconds": 48004.698458
        },
        {
          "page": 322.3,
          "seconds": 48488.880454
        },
        {
          "page": 325,
          "seconds": 48915.105442
        },
        {
          "page": 326.7,
          "seconds": 49169.549433
        },
        {
          "page": 328.6,
          "seconds": 49455.851429
        },
        {
          "page": 333.3,
          "seconds": 50124.958367
        },
        {
          "page": 340.2,
          "seconds": 51035.97034
        },
        {
          "page": 345.6,
          "seconds": 51877.925306
        },
        {
          "page": 348.4,
          "seconds": 52305.637279
        },
        {
          "page": 351.4,
          "seconds": 52775.980272
        },
        {
          "page": 354.8,
          "seconds": 53300.426259
        },
        {
          "page": 357.5,
          "seconds": 53699.577234
        },
        {
          "page": 359.9,
          "seconds": 54037.381224
        },
        {
          "page": 362.5,
          "seconds": 54420.69619
        },
        {
          "page": 365.2,
          "seconds": 54841.67415
        },
        {
          "page": 368,
          "seconds": 55269.478141
        },
        {
          "page": 371.3,
          "seconds": 55760.580136
        },
        {
          "page": 373.5,
          "seconds": 56087.610113
        },
        {
          "page": 375.9,
          "seconds": 56493.727075
        },
        {
          "page": 379.3,
          "seconds": 57016.687075
        },
        {
          "page": 381.8,
          "seconds": 57382.959048
        },
        {
          "page": 384.4,
          "seconds": 57781.228027
        },
        {
          "page": 386.7,
          "seconds": 58133.939002
        },
        {
          "page": 390.4,
          "seconds": 58707.24
        },
        {
          "page": 392.7,
          "seconds": 59052.613968
        },
        {
          "page": 398,
          "seconds": 59852.634921
        },
        {
          "page": 400.2,
          "seconds": 60153.286893
        },
        {
          "page": 402.9,
          "seconds": 60564.326893
        },
        {
          "page": 405.7,
          "seconds": 60972.76585
        },
        {
          "page": 408.8,
          "seconds": 61468.372834
        },
        {
          "page": 410.7,
          "seconds": 61760.525805
        },
        {
          "page": 413.1,
          "seconds": 62109.335782
        },
        {
          "page": 416.3,
          "seconds": 62597.83678
        },
        {
          "page": 420.7,
          "seconds": 63298.986757
        },
        {
          "page": 422.8,
          "seconds": 63633.586757
        },
        {
          "page": 425.1,
          "seconds": 63984.486712
        },
        {
          "page": 427.8,
          "seconds": 64390.928707
        },
        {
          "page": 430.2,
          "seconds": 64739.877687
        },
        {
          "page": 432.3,
          "seconds": 65054.879683
        },
        {
          "page": 434.9,
          "seconds": 65440.052653
        },
        {
          "page": 438.6,
          "seconds": 65991.433651
        },
        {
          "page": 442.2,
          "seconds": 66525.63161
        },
        {
          "page": 444.9,
          "seconds": 66953.017596
        },
        {
          "page": 447.5,
          "seconds": 67352.075556
        },
        {
          "page": 450.5,
          "seconds": 67798.780544
        },
        {
          "page": 453.8,
          "seconds": 68307.065533
        },
        {
          "page": 456.7,
          "seconds": 68754.514512
        },
        {
          "page": 458.7,
          "seconds": 69066.172472
        },
        {
          "page": 463.5,
          "seconds": 69804.288435
        },
        {
          "page": 466.1,
          "seconds": 70207.201406
        },
        {
          "page": 473.1,
          "seconds": 71257.811383
        },
        {
          "page": 475.9,
          "seconds": 71651.668345
        },
        {
          "page": 479.8,
          "seconds": 72220.185306
        },
        {
          "page": 482.3,
          "seconds": 72597.927302
        },
        {
          "page": 484.8,
          "seconds": 72976.830295
        },
        {
          "page": 487.6,
          "seconds": 73400.733288
        },
        {
          "page": 489.6,
          "seconds": 73708.722268
        },
        {
          "page": 492.1,
          "seconds": 74068.724263
        },
        {
          "page": 497.2,
          "seconds": 74817.986213
        },
        {
          "page": 500.9,
          "seconds": 75397.835193
        },
        {
          "page": 505,
          "seconds": 75996.07415
        },
        {
          "page": 507.8,
          "seconds": 76415.101134
        },
        {
          "page": 510.4,
          "seconds": 76786.1561
        },
        {
          "page": 512.4,
          "seconds": 77082.48907
        },
        {
          "page": 515.9,
          "seconds": 77561.795057
        },
        {
          "page": 518.3,
          "seconds": 77912.927029
        },
        {
          "page": 523.1,
          "seconds": 78616.352018
        },
        {
          "page": 526.5,
          "seconds": 79118.181995
        },
        {
          "page": 529.4,
          "seconds": 79546.589977
        },
        {
          "page": 531.8,
          "seconds": 79899.02195
        },
        {
          "page": 534.4,
          "seconds": 80277.135918
        },
        {
          "page": 541,
          "seconds": 81234.308889
        },
        {
          "page": 543.4,
          "seconds": 81587.901859
        },
        {
          "page": 546.4,
          "seconds": 82045.102857
        },
        {
          "page": 549.2,
          "seconds": 82463.804853
        },
        {
          "page": 551.6,
          "seconds": 82819.952834
        },
        {
          "page": 554.1,
          "seconds": 83187.570794
        },
        {
          "page": 557.2,
          "seconds": 83654.10576
        },
        {
          "page": 559.8,
          "seconds": 84021.770748
        },
        {
          "page": 562.3,
          "seconds": 84385.48771
        },
        {
          "page": 566.6,
          "seconds": 84862.796689
        },
        {
          "page": 568.6,
          "seconds": 85148.587664
        },
        {
          "page": 570.9,
          "seconds": 85495.586621
        },
        {
          "page": 573.1,
          "seconds": 85827.167619
        },
        {
          "page": 575.8,
          "seconds": 86210.110612
        },
        {
          "page": 577.9,
          "seconds": 86566.629569
        },
        {
          "page": 580.5,
          "seconds": 86933.876553
        },
        {
          "page": 583,
          "seconds": 87325.086531
        },
        {
          "page": 585.4,
          "seconds": 87689.918503
        },
        {
          "page": 587.5,
          "seconds": 88019.363492
        },
        {
          "page": 590.1,
          "seconds": 88384.474467
        },
        {
          "page": 592.4,
          "seconds": 88724.135465
        },
        {
          "page": 594.7,
          "seconds": 89075.128435
        },
        {
          "page": 597.4,
          "seconds": 89482.685397
        },
        {
          "page": 599.9,
          "seconds": 89837.161361
        },
        {
          "page": 602.1,
          "seconds": 90153.974331
        },
        {
          "page": 604.6,
          "seconds": 90493.961315
        },
        {
          "page": 606.5,
          "seconds": 90770.975283
        },
        {
          "page": 609.2,
          "seconds": 91192.185261
        },
        {
          "page": 611.7,
          "seconds": 91557.06322
        },
        {
          "page": 614.8,
          "seconds": 92008.227211
        },
        {
          "page": 616.8,
          "seconds": 92337.207211
        },
        {
          "page": 620.4,
          "seconds": 92867.179184
        },
        {
          "page": 624.8,
          "seconds": 93549.057143
        },
        {
          "page": 627.4,
          "seconds": 93946.211111
        },
        {
          "page": 630.7,
          "seconds": 94439.728073
        },
        {
          "page": 633.2,
          "seconds": 94817.192063
        },
        {
          "page": 636.6,
          "seconds": 95326.777052
        },
        {
          "page": 638.1,
          "seconds": 95548.435011
        },
        {
          "page": 640.6,
          "seconds": 95919.442993
        },
        {
          "page": 643.6,
          "seconds": 96375.203991
        },
        {
          "page": 645.7,
          "seconds": 96756.196961
        },
        {
          "page": 648.2,
          "seconds": 97147.684943
        },
        {
          "page": 650.9,
          "seconds": 97575.1639
        },
        {
          "page": 653.9,
          "seconds": 98093.990884
        },
        {
          "page": 656.3,
          "seconds": 98476.887846
        },
        {
          "page": 658.7,
          "seconds": 98864.335828
        },
        {
          "page": 664.1,
          "seconds": 99676.429796
        },
        {
          "page": 666.6,
          "seconds": 100058.072789
        },
        {
          "page": 668.9,
          "seconds": 100407.393787
        },
        {
          "page": 671.3,
          "seconds": 100783.788753
        },
        {
          "page": 675.1,
          "seconds": 101332.197732
        },
        {
          "page": 676.8,
          "seconds": 101669.954694
        },
        {
          "page": 683,
          "seconds": 102487.947664
        },
        {
          "page": 685.8,
          "seconds": 102913.42966
        },
        {
          "page": 688.5,
          "seconds": 103294.32966
        }
      ]
    }
  }
};
